spring:
  datasource:
    url: jdbc:mysql://localhost:3306/entry
    username: root
    password: wjdgus2007?
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
key:
  secretKey: ${secretKey}
jwt:
  header: Authorization
  prefix: Bearer
  secret: ajsdklfjasdklfjasldkfdasjlasdjfklasdjlasndflasjdkfasdkfnasdasjidkflajsdkfahsdfjka
  accessExpiration: 3600
  refreshExpiration: 271000

server:
  port: 8080