spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.65.160.119:3306/cmd?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: b57062562@gmail.com
    password: qbtbnshntzeuzdeh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
key:
  secretKey: ${secretKey}
jwt:
  header: Authorization
  prefix: Bearer
  secret: lhjljlasndflasjdkfasdkfnasdasjidkflajsdkfahsdfjkafewfawefwaefeawfw
  accessExpiration: 3600
  refreshExpiration: 271000



server:
  port: 8080

logging:
  level:
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: OFF

