spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.25.221.219:3306/cmd?useSSL=false&autoReconnect=true
    username: root
    password: wjdgus2007?
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: ${REDIS_HOST:localhost}
    port: 6379
key:
  secretKey: ${secretKey}
jwt:
  header: Authorization
  prefix: Bearer
  secret: lhjljlasndflasjdkfasdkfnasdasjidkflajsdkfahsdfjkafewfawefwaefeawfw
  accessExpiration: 3600
  refreshExpiration: 271000

mail:
  host: smtp.gamil.com
  port: 587
  username: 4mj.eo@dsm.hs.kr
  password: Rlaaudwls1!
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true

server:
  port: 8080

logging:
  level:
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: OFF

