spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmd?useSSL=false
    username: root
    password: ${password:wjdgus2007?}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: localhost
    port: 6379
key:
  secretKey: ${secretKey}
jwt:
  header: Authorization
  prefix: Bearer
  secret: lhjljlasndflasjdkfasdkfnasdasjidkflajsdkfahsdfjkafewfawefwaefeawfw
  accessExpiration: 3600
  refreshExpiration: 271000

mail:
  smtp:
    auth : true
    starttls:
      required : true
      enable : true
    socketFactory:
      class : javax.net.ssl.SSLSocketFactory
      fallback : false
      port : 465
    port : 465

AdminMail:
  id : b57062562@gmail.com
  password : qbtbnshntzeuzdeh

server:
  port: 8080

logging:
  level:
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: OFF

